### ISSUE TITLE
Errors when using an invalid API key or when performing excessive requests

### ISSUE THREAD

**Issue by ftm** [ftm/pyeactivities#1]
Authentication errors returned by the API are not handled by the wrapper. It attempts to parse them and then throws errors.

Using no API key or an invalid API key should return a 401 response such as:
```
HTTP 401 Unauthorised
{
    "Message": "Please specify a valid API key"
}
```

Repeated failed attempts and excessive requests also trigger a 403 response:
```
HTTP 403 Forbidden
{
    "Message": "IP address xxx.xxx.xxx.xxx has been banned until 17/04/2019 00:53:40 for making repeated failed attempts."
}
```

The error thrown when using an invalid API key is:
```
Traceback (most recent call last):
  File "usage.py", line 5, in <module>
    my_csp = eactivities.get_csps()[0]
  File "/home/fraser/.local/share/virtualenvs/pyeactivities-sandbox-lT5yn1P_/lib/python3.7/site-packages/pyeactivities/eactivities.py", line 15, in get_csps
    for csp in csps_response
  File "/home/fraser/.local/share/virtualenvs/pyeactivities-sandbox-lT5yn1P_/lib/python3.7/site-packages/pyeactivities/eactivities.py", line 15, in <listcomp>
    for csp in csps_response
TypeError: string indices must be integers
```

**Comment by ftm** [comment]
To fix this: in the HTTP client after performing the GET request, the status code of the response should be checked and a more helpful error should be raised.
